### PR TITLE
Added 2 functions

### PR DESCRIPTION
**Pull request by physje**
added 2 functions to use other RWS API services
- _measurements_available_
   checks if there are measurements available for location, in the given period of time
- _last_observation_
  gives the last observation for a given location

### CODE REVIEW

**Comment by physje** [comment]
Can you please merge this pull request and upload the updated package to pypi.org?
For an external project I only can use packages from pypi.org.

**Comment by physje** [comment]
Is this repository still being maintained?

**Comment by veenstrajelmer** [comment]
@physje to avoid code duplication I made added the functions you need in a bit more modular way. With the master branch it is now possible to get the latest measurements with: `ddlpy.measurements_latest()`. This was added in https://github.com/openearth/ddlpy/pull/35.

Furthermore, `ddlpy.measurements()` now first checks if there are measurements available, before starting the month-loop. If nothing is available, it returns an empty list just as it did before. If you need the boolean yourself, you could use the private function `ddlpy.ddlpy._measurements_available()`. This was added in https://github.com/openearth/ddlpy/pull/35.

Please let us know if this suits your need so we can close this PR. After some additional updates, we can make a new PyPI release also.

**Comment by physje** [comment]
@veenstrajelmer `ddlpy.measurements_latest()` and `ddlpy.ddlpy._measurements_available()` fulfill my needs.
So I'll close this pull request.

**Pull request closed without merging**
